name: tazaqala
description: "Мобильное приложение для управления жалобами жителей города"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.3.0
  geolocator: ^14.0.2
  image_picker: ^1.1.0
  fluttertoast: ^8.2.1
  go_router: ^13.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  retrofit: ^4.0.1
  retrofit_generator: ^5.0.0
  logger: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  cached_network_image: ^3.3.0
  permission_handler: ^11.0.1
  flutter_form_builder: ^10.2.0
  flutter_spinkit: ^5.2.0
  pull_to_refresh: ^2.0.0
  lottie: ^2.7.0
  dotted_border: ^3.1.0
  camera: ^0.11.0+1
  url_launcher: ^6.2.1
  fl_chart: ^0.65.0
  shared_preferences: ^2.1.1
  crypto: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
